name: build-blog

on:
  workflow_dispatch:
    inputs:
      message:
        description: test
        required: false

  issues:
    types: [labeled]

jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name, 'Blog') && contains(github.event.issue.labels.*.name, 'Publishing')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Navigate to Actions Folder and Install Dependencies
        run: |
          cd ./actions
          pnpm install --no-frozen-lockfile

      - name: Generate Blog Markdown File
        run: |
          cd ./actions
          npm run build
          node dist/makeBlog.js
        # if: github.event.issue.number == ${{ env.BOOKMARK_ISSUE_ID }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

